name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.NGINX_EC2_SSH_KEY }}

    - name: Clean up old files on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@54.94.254.215 "sudo rm -rf /var/www/html/*"

    - name: Deploy to EC2
      run: |
        rsync -avz --delete ./ ubuntu@54.94.254.215:/var/www/html/
        ssh -o StrictHostKeyChecking=no ubuntu@54.94.254.215 'sudo systemctl reload nginx'

    - name: Check Nginx status
      run: ssh -o StrictHostKeyChecking=no ubuntu@54.94.254.215 'sudo systemctl status nginx'
